name: 'test'

on:
    push:
    pull_request:
    schedule:
      - cron: '0 15 * * *'

env:
  CI: true

jobs:

  lin:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      DOCKER_IMAGE: ghdl/vunit:llvm
    steps:
    - uses: actions/checkout@v2
    - run: docker pull $DOCKER_IMAGE
    - run: |
        docker run --rm -tv $(pwd):/src -w /src -e CI $DOCKER_IMAGE sh -c "
        apt update -qq
        apt install -y imagemagick
        python3 -m pip install pytest --progress-bar off
        python3 -m pytest -v -s -ra test.py --color=yes
        "

  win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - env:
        WINDOWS_RELEASE: 0.37-mingw64-llvm
      shell: bash
      run: |
        curl -fsSL -o ghdl.zip https://github.com/ghdl/ghdl/releases/download/v0.37/ghdl-${WINDOWS_RELEASE}.zip
        7z x ghdl.zip "-o../ghdl-tmp" -y
        mv ../ghdl-tmp/GHDL/${WINDOWS_RELEASE}/ ../ghdl
        rm -rf ../ghdl-tmp ghdl.zip
        export PATH=$PATH:$(pwd)/../ghdl/bin
        python -m pip install pytest vunit_hdl --progress-bar off
        python -m pytest -v -s -ra test.py --color=yes
