name: 'test'

on:
    push:
    pull_request:

env:
  CI: true
  DOCKER_BUILDKIT: 1
  DOCKER_IMAGE: ghdl/ghdl:buster-llvm-7

jobs:

  vhpidirect:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        max-parallel: 4
        matrix:
          task: [
            vhpidirect/quickstart/random,
            vhpidirect/quickstart/math,
            vhpidirect/quickstart/customc,
            vhpidirect/arrays/intvectorgeneric,
            vhpidirect/wrapping/basic,
            vhpidirect/wrapping/time,
            vhpidirect/linking/bind,
            vhpidirect/shared/shlib,
            vhpidirect/shared/dlopen,
            vhpidirect/shared/shghdl,
          ]
    steps:
    - uses: actions/checkout@v1
    - run: docker pull $DOCKER_IMAGE
    - run: docker run --rm -tv $(pwd):/src $DOCKER_IMAGE /src/${{ matrix.task}}/run.sh
